---

# Confused about Ansible roles?
# I was too. They're basically just a bit of naming convention magic.
# http://docs.ansible.com/playbooks_roles.html#roles


### Bootstrap the {{ deploy }} user.
### You must call this playbook with an admin user.
### (The included Vagrantfile will use -u vagrant. For DigitalOcean, use -u root.)

- hosts: all
  sudo: True
  # user: intentionally blank
  roles:
    - { role: create-deploy-user, tags: ['create-deploy-user'] }


- hosts: all
  remote_user: "{{ deploy }}"
  roles:
    ### Server provisioning roles:
    - { role: linux-prereqs, tags: ['linux-prereqs'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: rbenv, tags: ['rbenv'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: papertrail, tags: ['papertrail'] }
    - { role: nginx-passenger, tags: ['nginx-passenger'] }

- hosts: all
  remote_user: "{{ deploy }}"
  roles:
    - { role: site-bikeways, tags: ['site-bikeways'] }
    - { role: site-ttchotline, tags: ['site-ttchotline'] }
