---
whereami: staging

# Unix user name to deploy as
deploy: staging0

# Crypted password for 'deploy' Unix user.
# To generate, use generate-crypted-password.py
password: $6$rounds=100000$meVqMOAJNEN26HJh$B6SNn0WofohE3rdCCqnZ14tydHPHidLx6l6k023BjQ1KwxWrxU2tAjOVh6WREMtpay/N9uYp.wkIFoapEXVOu0

# Ruby version to install
ruby_version: 2.1.5
rbenv_makeopts: ""

# Papertrail logging
# e.g. @logs.papertrailapp.com:1234
papertrail_log_dest: "@logs.papertrailapp.com:46606"
