---
ttchotline_rails_env: staging

# Used as nginx site name, rails directory, among other things
ttchotline_full_app_name: ttchotline

# Used by nginx for the vhost of the server
ttchotline_server_name: sttc.jbinto.ca

# Postgresql database settings
ttchotline_database_host: localhost
ttchotline_database_port: 5432
ttchotline_database_name: ttchotline_staging
ttchotline_database_user: ttchotline_staging
ttchotline_database_password: "{{ lookup('password', inventory_dir + '/credentials/' + ttchotline_database_user + '.postgresql.txt length=20') }}"

# Password is generarted on the fly, and later injected into database.yml.
# See ./credentials/ for previously generated passwords.
# This directory is ignored by Git.
