---
bikeways_rails_env: staging

# Used as nginx site name, rails directory, among other things
bikeways_full_app_name: bikeways

# Used by nginx for the vhost of the server
bikeways_server_name: staging.416.bike

# Postgresql database settings
bikeways_database_host: localhost
bikeways_database_port: 5432
bikeways_database_name: bikeways_staging
bikeways_database_user: bikeways_staging
bikeways_database_password: "{{ lookup('password', inventory_dir + '/credentials/' + bikeways_database_user + '.postgresql.txt length=20') }}"

# Password is generarted on the fly, and later injected into database.yml.
# See ./credentials/ for previously generated passwords.
# This directory is ignored by Git.
